[build]
  base = "skrepayshop-platform"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_PUBLIC_PLATFORM_NAME = "SkrepayShop"
  NEXT_PUBLIC_PLATFORM_URL = "https://strong-cascaron-2e0511.netlify.app"
  NEXT_PUBLIC_ADMIN_URL = "https://luigi-games-api1.onrender.com/app"
  MEDUSA_BACKEND_URL = "https://luigi-games-api1.onrender.com"
  NEXT_PUBLIC_DEMO_STORE_URL = "https://luigigame.com"
  NEXT_PUBLIC_FUTURE_DOMAIN = "https://skrepay.com"
